### ISSUE TITLE
Can't mount userspace after reboot on ipad 7th generation.

### ISSUE THREAD

**Issue by Kaiserreich-Unofficial** [nekoJB/BugTracker#2]
Thanks for the effort in developing such a rootful jailbreak tool. I've encontered some bugs when I tried to jailbreak my ipad 7th generation.  After I tap the "jailbreak" button, everything seems work fine. But when My device auto reboot to the bootloader mode (maybe DFU mode, I'm not quite sure), which has a NekoJB logo on the screen. The console report an error that /dev/disk0s1s0 does not exist and then abort. The processor of my ipad is A10, the arch is arm64, the iOS version is iOS 15.0.1. Could u pls fix this bug?

**Comment by 25hawkeye** [comment]
I got the same error, this time being /dev/disk0s1s8. I’m not sure if I’m supposed to have palera1n rootful also installed, as I tried both with and with yet no results. (Nekojb 2.0.11 IPod touch 7th gen IOS 15.8.2)
